# Site settings
title: Problema 2 checkpoint 3
email: diogo.lima@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
 site sobre tarefas realizadas na disciplina de análise de dados.
baseurl: "/AnaliseDeDados/Problema1/checkpoint3"
url: "https://diogoflorencio.github.io/AnaliseDeDados/Problema1/checkpoint3/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  diogoflorencio
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
