---
title: "Predição de Deputados Eleitos"
author: "Diogo Florêncio"
date: "1 de março de 2018"
output:
  html_notebook:
    theme: readable 
    toc: true
    toc_float: true
    fig_width: 5
    fig_height: 4
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(caret)
options(scipen = 4) #escala dos valores exibidos
treino <- read.csv("../dados/train_lab4.csv", encoding = "UTF-8")
```

###Há desbalanceamento das classes (isto é, uma classe tem muito mais instâncias que outra)? Em que proporção? Quais efeitos colaterais o desbalanceamento de classes pode causar no classificador?.

###Treine: um modelo de regressão logística, uma árvore de decisão e um modelo de adaboost. Tune esses modelos usando validação cruzada e controle overfitting se necessário, considerando as particularidades de cada modelo.

###Reporte acurácia, precision, recall e f-measure no treino e validação. Como você avalia os resultados? Justifique sua resposta.

###Interprete as saídas dos modelos. Quais atributos parecem ser mais importantes de acordo com cada modelo? Crie pelo menos um novo atributo que não está nos dados originais e estude o impacto desse atributo.